spring.application.name=crecheconecta

spring.datasource.url=jdbc:postgresql://localhost:5432/crecheconecta
spring.datasource.username=postgres
spring.datasource.password=2302123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=true

server.error.include-message=never
server.error.include-stacktrace=never
