spring.application.name=crecheconecta

saude.criptografia.chave=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

spring.datasource.url=jdbc:postgresql://localhost:5433/CrecheConecta
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.path=/swagger-ui.html

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=true
spring.flyway.validate-on-migrate=false

server.error.include-message=never
server.error.include-stacktrace=never
