spring.application.name=crecheconecta-camadas
spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/crecheconecta_camadas
spring.datasource.username=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
